### ISSUE TITLE
XMLResultsExporter only available with Newhall v1.6.1 JAR

### ISSUE THREAD

**Issue by dylanbeaudette** [ncss-tech/jNSMR#3]
Looks like the current GH version is using `newhall-1.6.4.jar`. Any plans to enable XML output, or is there a better way?

**Comment by brownag** [comment]
The older JAR files are included in the Java data in the package, so all you need to do is set this package option prior to loading {jNSMR}:

```r
options(jNSMR.JAR_SUFFIX="-1.6.1")
library(jNSMR)
```

This could be better documented. I have no plans to re-create the XML parsing code in modern Java for the >1.6.1 builds that support batching, but didn't think anyone would need it. Its a neat format, though, and the output for a single site analysis is quite comprehensive. What are you using it for, if I may ask?

**Comment by dylanbeaudette** [comment]
No problem, I don't need it. Was just following some examples and thinking about the possible output formats. A note in the docs would be good. Thanks.

Batch mode was more appropriate for the task at hand, using that.
